#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe orte 1
#$ -N BC1-1-RT 
#$ -v LD_LIBRARY_PATH,OPAL_EXE_PATH,OPENMPI,REG_TEST_DIR

MACHINE_FILE=$TMPDIR/machinefile
awk '/^felsim/ {print $1" slots="$2}' $PE_HOSTFILE > $MACHINE_FILE 
cp $MACHINE_FILE machinefile.last

cd $REG_TEST_DIR
OPAL="$OPAL_EXE_PATH/opal BC1-1.in --commlib mpi --info 9 --warn 0 2>&1"
CMD="$OPENMPI/bin/mpirun -x LD_LIBRARY_PATH -machinefile $MACHINE_FILE -np $NSLOTS $OPAL "
$CMD
