#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe orte 4
#$ -N ParallelPlateVaughan1-RT
#$ -v OPENMPI,LD_LIBRARY_PATH,OPAL_EXE_PATH,REG_TEST_DIR

MACHINE_FILE=$TMPDIR/machinefile
awk '/^merlin/ {print $1" slots="$2}' $PE_HOSTFILE > $MACHINE_FILE 
cp $MACHINE_FILE machinefile.last

cd $REG_TEST_DIR
OPAL="$OPAL_EXE_PATH/opal ParallelPlateVaughan1.in --commlib mpi --info 3 --warn 0 2>&1"
CMD="$OPENMPI/bin/mpirun -x LD_LIBRARY_PATH -machinefile $MACHINE_FILE -np $NSLOTS $OPAL "
$CMD
